"""Initial

Revision ID: db1e13ec28c0
Revises: 
Create Date: 2024-10-18 04:14:21.371458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1e13ec28c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('clockify_token', sa.String(), nullable=False),
    sa.Column('clockify_user_id', sa.String(), nullable=False),
    sa.Column('clockify_workspace_id', sa.String(), nullable=False),
    sa.Column('youtrack_token', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clockify_token'),
    sa.UniqueConstraint('clockify_user_id'),
    sa.UniqueConstraint('youtrack_token')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtrack_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtrack_id')
    )
    op.create_table('work_item_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('youtrack_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('youtrack_id')
    )
    op.create_table('project_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('default_work_item_type_id', sa.Integer(), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_work_item_type_id'], ['work_item_type.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_member_id', sa.Integer(), nullable=False),
    sa.Column('clockify_time_entry_id', sa.String(), nullable=False),
    sa.Column('youtrack_id', sa.String(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('work_item_type_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_member_id'], ['project_member.id'], ),
    sa.ForeignKeyConstraint(['work_item_type_id'], ['work_item_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clockify_time_entry_id'),
    sa.UniqueConstraint('youtrack_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_item')
    op.drop_table('project_member')
    op.drop_table('work_item_type')
    op.drop_table('project')
    op.drop_table('employee')
    # ### end Alembic commands ###
