"""Employees soft delete

Revision ID: eec07be171f9
Revises: 6dbc5c7cb1df
Create Date: 2024-11-15 13:10:33.785650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec07be171f9'
down_revision: Union[str, None] = '6dbc5c7cb1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'deleted_at')
    # ### end Alembic commands ###
